apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: backend-network-policy
  namespace: {{ .Values.namespace }}

spec:
  podSelector:
    matchLabels:
      app: backend

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.targetPort }}

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mongodb
      ports:
        - protocol: TCP
          port: {{ .Values.mongodb.service.port }}
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: mongodb-network-policy
  namespace: {{ .Values.namespace }}

spec:
  podSelector:
    matchLabels:
      app: mongodb

  policyTypes:
    - Ingress

  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: {{ .Values.mongodb.service.port }}

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy

metadata:
  name: frontend-network-policy
  namespace: {{ .Values.namespace }}

spec:
  podSelector:
    matchLabels:
      app: frontend

  policyTypes:
    - Ingress
    - Egress

  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.frontend.service.targetPort }}

  egress:
    - to:
        - podSelector:
            matchLabels:
              app: backend
      ports:
        - protocol: TCP
          port: {{ .Values.backend.service.targetPort }}
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
