apiVersion: v1
kind: Secret

metadata:
  name: mern-secret
  namespace: mern

type: Opaque

stringData:

  # MongoDB Username
  MONGO_USERNAME: admin

  # MongoDB Password
  MONGO_PASSWORD: admin123

  # MongoDB Database
  MONGO_DATABASE: todo

  # Complete MongoDB Connection String
  MONGO_CONN_STR: mongodb://admin:admin123@mongodb-service:27017/todo?authSource=admin